name: Release

on:
  release:
    branches: [main]
    types: [released]
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to update to'
        default: 'v2'
        required: true
      ref:
        description: 'which branch to update the tag on'
        default: 'main'
        required: true

permissions:
  contents: write

jobs:
  re-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
      with:
        persist-credentials: true # needed for `git push`
        fetch-depth: 0
        ref: ${{ inputs.ref }}
    - name: Config git name and email
      run: |
        git config user.name 'github-actions'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - name: Update rolling tag
      run: |
        # Get the major version from the latest tag
        MAJOR_VERSION=`git tag --list --sort=-v:refname | head -n1 | cut -d. -f1`
        git tag --force --annotate ${{ inputs.tag || '$MAJOR_VERSION' }} --message 'Retag ${{ inputs.tag || '$MAJOR_VERSION' }}'
        git push origin ${{ inputs.tag || '$MAJOR_VERSION' }} --force
