name: "Check python code"

on: [push, pull_request]

jobs:
  using-pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pylint and action deps
        run: |
          python3 -m pip install --upgrade pylint
          python3 -m pip install -r requirements.txt
      - name: run pylint
        run: |
          pylint python_action/**
          pylint setup.py
